# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-12 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='db_assign',
            field=models.CharField(blank=True, default='None', max_length=150, null=True),
        ),
    ]
